### ISSUE TITLE
Deploy v0 of Leios simulator

### ISSUE THREAD

**Issue by abailly-iohk** [input-output-hk/ouroboros-leios#7]
* [x] legend/description
  * [x] deploying => CI
  * [x] linking from the site
  * [x] explaining static parameters
  * [x] multithreaded server -> one simulation per WS connection
  * [x] start/stop/play/resume

**Comment by abailly-iohk** [comment]
I have polished a bit the UI and added some metrics, but those don't make sense to me: I would expected throughput, computed as the total amount of endorsed data divided by time to be in the order of $C \lambda / (\lambda + 1)$

![Screenshot 2024-07-18 at 15 24 27](https://github.com/user-attachments/assets/e199bc5b-2efd-4e74-872e-69fcf406ab7c)

**Comment by dnadales** [comment]
Since the first version of the simulator is deployed, I think we can close this one and open smaller follow-up issues (like what was mentioned in the previous comment). Feel free to re-open if you think this is not okay, @abailly-iohk.
